### ISSUE TITLE
Newly broken tests

### ISSUE THREAD

**Issue by facelessuser** [color-js/color.js#524] opened 2024-05-24 01:03 UTC
Object construction

<img width="1314" alt="Screenshot 2024-05-23 at 7 01 23 PM" src="https://github.com/color-js/color.js/assets/1055125/ef5615b6-dd18-44f7-850d-af44e8020564">

Parsing. I think these are new? Are they supposed to be failing?

<img width="1323" alt="Screenshot 2024-05-23 at 7 03 10 PM" src="https://github.com/color-js/color.js/assets/1055125/13be95ad-cbb1-448d-ace4-9945bc9a3651">

**Comment by LeaVerou** [comment] 2024-05-24 01:35
It seems to be an hTest bug, not actual failing tests.

**Comment by facelessuser** [comment] 2024-05-24 02:31
Ah, in that case, feel free to close unless you want to track resolution of the hTest issue.

**Comment by DmitrySharabin** [comment] 2024-05-24 22:20
> It seems to be an hTest bug, not actual failing tests.

My investigation showed that the issue is that the test suite uses, for some reason, the old version of hTest—it uses the old version of the `equals()` function:


<img width="1528" alt="SCR-20240525-bdcq" src="https://github.com/color-js/color.js/assets/9166277/9959808b-30a1-4b33-9abb-3e74b7869b0f">


Is there a chance that `htest.dev` serves a cached version of hTest used by this HTML-first test suite?

https://github.com/color-js/color.js/blob/c6a19f83ddf28d7ae5805c98aec3d74162fbb9fd/test/index.html#L7

**Comment by LeaVerou** [comment] 2024-05-25 17:44
This is not an HTML-first testsuite, it's an HTML adapter for displaying the JS-first tests.

We are doing a weird thing to import from node_modules locally and from the htest.dev website remotely which I plan to replace with a redirect. Not sure if that will make a difference.

**Comment by LeaVerou** [comment] 2024-05-25 17:46
A-ha! htest.dev stopped deploying 2 months ago, that must be it!

**Comment by LeaVerou** [comment] 2024-05-25 17:56
Turns out it was that I upgraded to 11ty 3.0 which requires Node > 18, and it was somehow set to Node 16. Fixed now!

**Comment by LeaVerou** [comment] 2024-05-25 17:57
Thanks @DmitrySharabin for investigating!

**Closed by LeaVerou** 2024-05-25 17:56 UTC
