### ISSUE TITLE
Gray color is not correctly cast to a string

### ISSUE THREAD

**Issue by star-over** [color-js/color.js#475] opened 2024-03-09 18:21 UTC
I noticed a problem when trying to use the API in the developer tools. 
Specifically, when I tried to convert the color 'gray' to HSL and then to a string, the result displayed 'none'. Other color names do not have this result.

```
(new Color("gray")).to("hsl").toString()
>> 'hsl(none 0% 50.196%)'
```

<img width="446" alt="image" src="https://github.com/color-js/color.js/assets/803639/24b66b9e-9610-4b83-b51f-9fbd453d55f5">

**Comment by facelessuser** [comment] 2024-03-09 18:53
What hue would you suggest gray has? The reason why you get an undefined hue (`none`) is because the color is achromatic and has no hue.

**Comment by star-over** [comment] 2024-03-10 05:29
I suggest use `0` instead `none` when color stringify. So, I expect `hsl(0 0% 50.196%)` but not a `hsl(none 0% 50.196%)`

**Comment by facelessuser** [comment] 2024-03-10 05:49
`none` is now supported in the CSS spec and has been implemented in a number of browsers. Gray doesn't actually have a red (0deg) hue, but regardless of technicalities of what is more correct, I can imagine some people desiring a way to serialize without `none`. There was an option to do so for some amount of time, but it was removed in https://github.com/color-js/color.js/commit/e28cd6a48922c525188f779506f6c204e4aecf40.

Below does look like a bug to me though. Undefined values should be handled before conversion, but that does not appear to be happening currently.

```
new Color("hsl(none 0% 50.196%)").to("srgb").toString()
>>> 'rgb(none none none)'
```

**Comment by star-over** [comment] 2024-03-10 05:56
I just fixed problem for a while with a `.toString().replaceAll("none", "0")` after any stringify.

**Comment by facelessuser** [comment] 2024-03-10 06:00
I personally think an option to allow omitting `none` in serialization seems reasonable, but the`none` conversion issue should definitely get fixed.

**Comment by facelessuser** [comment] 2024-03-10 14:43
I've created a PR (#476) to adjust the bad "none" handling across the library.

@svgeesus and @LeaVerou would need to make a decision on whether it is desired to expose conditional "none" serialization. If they decided that they wanted to move forward with this, I'd be happy to make the PR.

**Comment by facelessuser** [comment] 2024-03-14 13:38
None bug has been fixed on main.  A new issue is opened that, when implemented, could solve the serialization request: https://github.com/color-js/color.js/issues/479. I will resolve this as a duplicate of that issue. I advise following that issue to stay on top of progress.

**Closed by facelessuser** 2024-03-14 13:38 UTC
